name: Build and Push Docker

on:
  push:
    branches:
      - main
    paths:
      - 'dotnet/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: .Net 8 Sdk with Node 20
        uses: docker/build-push-action@v2
        with:
          context: ./dotnet
          file: ./dotnet/NetSdk8Node20/Dockerfile
          push: true
          tags: hugohomesquita/sdk8-node20:latest
